version: '3.1'

services:
  mongo:
    image: mongo:7.0.6-windowsservercore-ltsc2022
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: foo
      MONGO_INITDB_ROOT_PASSWORD: bar