name: Codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0'
      - name: Install dependencies
        run: dotnet restore && dotnet tool restore 
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Generate Coverage Report
        run: dotnet dotcover test --dcReportType=XML
      - name: Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./dotCover.Output.xml
